package com.digitalizha.apkcloner;

import android.util.Base64;

import java.io.ByteArrayInputStream;
import java.security.KeyFactory;
import java.security.PrivateKey;
import java.security.cert.CertificateFactory;
import java.security.cert.X509Certificate;
import java.security.spec.PKCS8EncodedKeySpec;

final class DebugKeyProvider {
    private DebugKeyProvider() {}

    // Debug key bawaan untuk menandatangani APK hasil clone.
    // Jangan dipakai untuk produksi / app penting. Semua hasil clone akan pakai signature baru ini.
    private static final String PRIVATE_KEY_PKCS8_BASE64 = "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCm3kjYVXzixcPqbZNDSSTlHmI0WNCGDrsXUjtmGCplcngkSzqSdJozvKOglSH3Xyh5z+EnxUODroPRPUPocPYJZLsY+R85nlon79TsZYIt9EGyTkPxyJ16DUMVEG2TbjSMJT1HjMnlS/9xUiYpWS6LK5lpV0NQsveUkHzUf7PuNXbQdIprxpWgq82NAlDhBIZ2Op14UAeU9sSZFFn1TZDa/wY3+9uYuOlKWxQfyBbAKplBzO8k/w3KYon8gYOCx+V9c6qzvB2cYw0ArSs8tk7Nkq3eyCWHNEU0C7fXNFz63Xvp3GwaR+CNc6JGk0IVZSNKE2Xdq48KHfgc1rl/VUuFAgMBAAECggEAJ+UIDHSv1XXLx73n0dPodsDDYNmFDS/zafl2iwunAzcRYzf7Km2nOkxU4H0XMFG3Vxwsq/n9ELwF9t4LYMS1BfznwGo7HWbvDhJIWTZRn9QAavVMSD+a6sXF7oDNecyE0qbKllMiJ+h6C2lFB2izeIF1fZpn1SDckU/UEGfxqDcMOgq59kPIdt/wPde/jxVsGikSbpmiddrrFHa/fInEmRHpb2VoZDkzT2GtRyt4W+iihinUZMHDSul+Fo8c6iDwQaw+gguMge3qrh3GfGYQcrabVRQB5HZfYdtc6eyibxxm+MiV5I/KSKsl/34YQzHAgoDqReIVeC12iqqw1WqwhwKBgQDQui9fVcayWYhOdCUinCPU1Zl83v9ZS7+NBI24dH7iZtGhP56Mnr4xYhtwa1yrR9lGF0FsuIRJb6c9kJlfHjT2W6Y28aFZtUYxfA6azQD0KSjZHzWalTDl8P7Y0kiTHdpdR51gBqMtE/0zxLphdKleuFnWt4bKbeQb+c+VVG8kNwKBgQDMqSd5Fg2AkPD509NlRGmRFGz/b+NE2o6ScMnIcPq2JuNIZ8mcn4UKKYE8akmn4jUqojXrUuH6AdqHkwJ/Ig3ZwmsVTPCtJtm6moODna8l31qLrfIfoFc9gLdLNUpZmO6pmRRV3gJbH+d3ikSmeXBpSjqOLh6BLUv5ygMKUXtoIwKBgQC0qlNSu5YOzbxT2+hAutGw6Wm/Ue3Hxu74Cpb4r60cHk8YuU5s/QI3EGobtnIxtzDzoDF6/4NRZRlnCoAWerjw/Ic0S5WTZnppXq3tg8BtlirLNF5bfQMkJKMR3YIABPj7gH9RnK0k2YZyhreknyvy1rK8TYKYOOIW7PWmlbzVpQKBgAeFD5Y7YTOgH7qONe46nUZfYcHg8pDNFv/6dO+QdyXKN/+pEJdYpSLCc6Usopgwj5OJckG7QeJVvxnMJQNW1PtzUUvvD8jM7KMWmk5ztMPHeSQ4t/TBh3MTD6kLxDeWju5cWYruJVgDzBVwVyVmwOKdf5lJyIUmjOwYqBPw+n/RAoGANLd6dg2XbuWkfiWT17/xteSCCu8R1pGRBxWUnZ8ltzPYHR/vw1Xobc5jLrBZ2TKKhQ+kJ8LhEZjvoI7oorAvrQfaW3ugy6cfmcg/kSicioRZvvNxCVPtrhqoq7vGB8NUT+pLYLFMd+DoGV8k86ruI7OeYpR6Hjdk96cZx1bZRLc=";

    private static final String CERT_X509_BASE64 = "MIIDWTCCAkGgAwIBAgIUBN8U0uCqWxByiOP8MpxDpeJbPPUwDQYJKoZIhvcNAQELBQAwOzEWMBQGA1UEAwwNQW5kcm9pZCBEZWJ1ZzEUMBIGA1UECgwLRGlnaXRhbGl6aGExCzAJBgNVBAYTAklEMCAXDTI2MDUzMTExNDYzNloYDzIwNTMxMDE2MTE0NjM2WjA7MRYwFAYDVQQDDA1BbmRyb2lkIERlYnVnMRQwEgYDVQQKDAtEaWdpdGFsaXpoYTELMAkGA1UEBhMCSUQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCm3kjYVXzixcPqbZNDSSTlHmI0WNCGDrsXUjtmGCplcngkSzqSdJozvKOglSH3Xyh5z+EnxUODroPRPUPocPYJZLsY+R85nlon79TsZYIt9EGyTkPxyJ16DUMVEG2TbjSMJT1HjMnlS/9xUiYpWS6LK5lpV0NQsveUkHzUf7PuNXbQdIprxpWgq82NAlDhBIZ2Op14UAeU9sSZFFn1TZDa/wY3+9uYuOlKWxQfyBbAKplBzO8k/w3KYon8gYOCx+V9c6qzvB2cYw0ArSs8tk7Nkq3eyCWHNEU0C7fXNFz63Xvp3GwaR+CNc6JGk0IVZSNKE2Xdq48KHfgc1rl/VUuFAgMBAAGjUzBRMB0GA1UdDgQWBBTppzj/Q28ryNcQkQopRkb4VFzW+DAfBgNVHSMEGDAWgBTppzj/Q28ryNcQkQopRkb4VFzW+DAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQBNYt6AsvKk79ZnS8OQi7ehSuGFMfInzOsFXPnJUYLydthJBW/yOLpvfhhrw66vvqluKkYexsQJMIIj2rz3tRzvOrPhpkYjD6kECwvHicfusuQrlC76Klu6kL5zMkfLSdB/E1NNGY6XfaDZP0PiozGWMdMR4iddoCuZEmFM3kO/iZDGzzPcXSVrjYQr8PyLMdM+5YeZsr7JSnoUcBJzkMw1KM+fYTNIUde4EO8UFNj4Aiy6GGcZFOh0CKmbsPivMX6QoGYX6AefjCrHpoUsP5BADtsNyuSB6/rpJcVo4FrH40c1EAHxscGw21zeatCkadb2SewllQfT+SgfUbrwhBJt";

    static PrivateKey privateKey() throws Exception {
        byte[] keyBytes = Base64.decode(PRIVATE_KEY_PKCS8_BASE64, Base64.DEFAULT);
        return KeyFactory.getInstance("RSA").generatePrivate(new PKCS8EncodedKeySpec(keyBytes));
    }

    static X509Certificate certificate() throws Exception {
        byte[] certBytes = Base64.decode(CERT_X509_BASE64, Base64.DEFAULT);
        CertificateFactory factory = CertificateFactory.getInstance("X.509");
        return (X509Certificate) factory.generateCertificate(new ByteArrayInputStream(certBytes));
    }
}
